### ISSUE TITLE
Menu display errors on ED64+ flashcart

### ISSUE THREAD

**Issue by sp2333** [celerizer/Press-F-Ultra#2]
Using an ED64+ flashcart, there are varying errors in displaying the game list menu within the emulator.

Using the Altra64 menu, the top part of the game list is cut off, as shown in the screen shot, with list display shifted to above the viewable area of the screen. Also, not all on the games list are displayed (Cutting off after the letter 'M' in my example.. maybe there is a limit to the number of games that can be displayed?)

Using the N64FlashCartMenu, the list fails to load correctly, and stalls on a blank black screen.

There are other reports of corrupted screens that I have not been able to replicate on my particular device, e.g,
https://krikzz.com/forum/index.php?topic=13267.0

Though when a game is loaded, is does seem to function perfectly from that point on. The screen area seems to only apply to the game list menu itself

![IMG_20241124_220204](https://github.com/user-attachments/assets/bd69ae7a-094c-4d08-8036-e4a739c15284)

**Comment by celerizer** [comment]
Hello. I've just published a new release that completely replaces the UI and should fix invalid read errors and misaligned margins. Let me know if this fixes the issue:

https://github.com/celerizer/Press-F-Ultra/releases/tag/r3

**Comment by celerizer** [comment]
I'm going to close this as this menu doesn't exist in the program anymore and the program in its current state has now been tested on multiple cart / loader combinations
