### ISSUE TITLE
Loader plugin support

### ISSUE THREAD

**Issue by celerizer** [celerizer/Press-F-Ultra#3]
Apparently most N64 flashcart loader programs allow for stamping a ROM file to a specific memory address and using the file extension to launch a suitable emulator (ie. `chf.z64`).

Supporting this would be a good feature to have, though Channel F ROMs do not have a header format like NES / SNES, so making sure the contents at the address are valid might be difficult.

**Comment by sp2333** [comment]
Just recently, the SMSplus64 emulator done this too, which could be of use to check in with.

https://github.com/fhoedemakers/smsplus64/issues/4

**Comment by celerizer** [comment]
Added with cdf0c67559a34c2c5df2ac2477ebe352df8c3823
